joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: Pan
    joint_speed: 1.0
    motor:
        id: 1
        init: 0
        min: 0
        max: 4095
        
joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: Tilt
    joint_speed: 1.0
    motor:
        id: 2
        init: 2047
        min: 0
        max: 4095